name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/actions/install

      - name: Create Release PR and publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'release: bump packages'
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          version: bun run version
          publish: bun run publish:all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true